
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'EndorserMobile' do
  config = use_native_modules!

  use_react_native!(:path => "../node_modules/react-native")

  target 'EndorserMobileTests' do
    inherit! :complete
    # Pods for testing
  end

  permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"

end

target 'EndorserMobile-tvOS' do
  # Pods for EndorserMobile-tvOS

  target 'EndorserMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
